version: '3'
services:
  aboba_db:
    container_name: aboba_db
    restart: always
    shm_size: 128mb
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
      - PGDATA:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: .docker/dev/api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.staging

  nginx:
    container_name: nginx
    build:
      context: .docker/dev/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
