apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aboba-app.fullname" . }}-minio
spec:
  replicas: {{ .Values.minio.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aboba-app.name" . }}-minio
  template:
    metadata:
      labels:
        app: {{ include "aboba-app.name" . }}-minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          env:
            - name: MINIO_ACCESS_KEY
              value: "{{ .Values.minio.accessKey }}"
            - name: MINIO_SECRET_KEY
              value: "{{ .Values.minio.secretKey }}"
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aboba-app.fullname" . }}-minio
spec:
  selector:
    app: {{ include "aboba-app.name" . }}-minio
  ports:
    - port: 9000
      targetPort: 9000
