apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: st-aboba-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: st.aboba
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-frontend
            port:
              number: 80
